[project]
name = "sturdy-potato"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.1",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "django-stubs[compatible-mypy]>=6.1.0",
    "djlint>=1.44.2",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.3",
]

[tool.ruff]
exclude = ["**/migrations/**"]

[tool.mypy]
mypy_path = ["potato"]
plugins = ["mypy_django_plugin.main"]
strict = true

[tool.django-stubs]
django_settings_module = "potato.settings"
