/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccessToken,
    AccessTokenFromJSON,
    AccessTokenToJSON,
} from '../models/AccessToken';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ProjectCreateInput,
    ProjectCreateInputFromJSON,
    ProjectCreateInputToJSON,
} from '../models/ProjectCreateInput';
import {
    type ProjectSchema,
    ProjectSchemaFromJSON,
    ProjectSchemaToJSON,
} from '../models/ProjectSchema';
import {
    type ProjectUpdateInput,
    ProjectUpdateInputFromJSON,
    ProjectUpdateInputToJSON,
} from '../models/ProjectUpdateInput';
import {
    type ReorderInput,
    ReorderInputFromJSON,
    ReorderInputToJSON,
} from '../models/ReorderInput';
import {
    type TaskCountSchema,
    TaskCountSchemaFromJSON,
    TaskCountSchemaToJSON,
} from '../models/TaskCountSchema';
import {
    type TodoCreateInput,
    TodoCreateInputFromJSON,
    TodoCreateInputToJSON,
} from '../models/TodoCreateInput';
import {
    type TodoSchema,
    TodoSchemaFromJSON,
    TodoSchemaToJSON,
} from '../models/TodoSchema';
import {
    type TodoUpdateInput,
    TodoUpdateInputFromJSON,
    TodoUpdateInputToJSON,
} from '../models/TodoUpdateInput';
import {
    type TokenObtainPair,
    TokenObtainPairFromJSON,
    TokenObtainPairToJSON,
} from '../models/TokenObtainPair';
import {
    type TokenPair,
    TokenPairFromJSON,
    TokenPairToJSON,
} from '../models/TokenPair';
import {
    type TokenRefresh,
    TokenRefreshFromJSON,
    TokenRefreshToJSON,
} from '../models/TokenRefresh';

export interface ApiProjectsCreateRequest {
    projectCreateInput: ProjectCreateInput;
}

export interface ApiProjectsDestroyRequest {
    id: number;
}

export interface ApiProjectsPartialUpdateRequest {
    id: number;
    projectUpdateInput: ProjectUpdateInput;
}

export interface ApiProjectsReorderCreateRequest {
    reorderInput: ReorderInput;
}

export interface ApiProjectsRetrieveRequest {
    id: number;
}

export interface ApiTasksCountRetrieveRequest {
    completed?: boolean | null;
}

export interface ApiTasksCreateRequest {
    todoCreateInput: TodoCreateInput;
}

export interface ApiTasksDestroyRequest {
    id: number;
}

export interface ApiTasksOpenListRequest {
    limit?: number | null;
}

export interface ApiTasksPartialUpdateRequest {
    id: number;
    todoUpdateInput: TodoUpdateInput;
}

export interface ApiTasksReorderCreateRequest {
    reorderInput: ReorderInput;
}

export interface ApiTasksRetrieveRequest {
    id: number;
}

export interface ApiTasksViewListRequest {
    view?: string;
    project?: number | null;
}

export interface ApiTokenCreateRequest {
    tokenObtainPair: TokenObtainPair;
}

export interface ApiTokenRefreshCreateRequest {
    tokenRefresh: TokenRefresh;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiProjectsCreate without sending the request
     */
    async apiProjectsCreateRequestOpts(requestParameters: ApiProjectsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectCreateInput'] == null) {
            throw new runtime.RequiredError(
                'projectCreateInput',
                'Required parameter "projectCreateInput" was null or undefined when calling apiProjectsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/projects/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateInputToJSON(requestParameters['projectCreateInput']),
        };
    }

    /**
     * Create Project
     */
    async apiProjectsCreateRaw(requestParameters: ApiProjectsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSchema>> {
        const requestOptions = await this.apiProjectsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }

    /**
     * Create Project
     */
    async apiProjectsCreate(requestParameters: ApiProjectsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSchema> {
        const response = await this.apiProjectsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProjectsDestroy without sending the request
     */
    async apiProjectsDestroyRequestOpts(requestParameters: ApiProjectsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Project
     */
    async apiProjectsDestroyRaw(requestParameters: ApiProjectsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiProjectsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Project
     */
    async apiProjectsDestroy(requestParameters: ApiProjectsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProjectsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiProjectsList without sending the request
     */
    async apiProjectsListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/projects/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Projects
     */
    async apiProjectsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectSchema>>> {
        const requestOptions = await this.apiProjectsListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectSchemaFromJSON));
    }

    /**
     * List Projects
     */
    async apiProjectsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectSchema>> {
        const response = await this.apiProjectsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProjectsPartialUpdate without sending the request
     */
    async apiProjectsPartialUpdateRequestOpts(requestParameters: ApiProjectsPartialUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectsPartialUpdate().'
            );
        }

        if (requestParameters['projectUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'projectUpdateInput',
                'Required parameter "projectUpdateInput" was null or undefined when calling apiProjectsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateInputToJSON(requestParameters['projectUpdateInput']),
        };
    }

    /**
     * Update Project
     */
    async apiProjectsPartialUpdateRaw(requestParameters: ApiProjectsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSchema>> {
        const requestOptions = await this.apiProjectsPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }

    /**
     * Update Project
     */
    async apiProjectsPartialUpdate(requestParameters: ApiProjectsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSchema> {
        const response = await this.apiProjectsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProjectsReorderCreate without sending the request
     */
    async apiProjectsReorderCreateRequestOpts(requestParameters: ApiProjectsReorderCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reorderInput'] == null) {
            throw new runtime.RequiredError(
                'reorderInput',
                'Required parameter "reorderInput" was null or undefined when calling apiProjectsReorderCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/projects/reorder/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderInputToJSON(requestParameters['reorderInput']),
        };
    }

    /**
     * Reorder Projects
     */
    async apiProjectsReorderCreateRaw(requestParameters: ApiProjectsReorderCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiProjectsReorderCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reorder Projects
     */
    async apiProjectsReorderCreate(requestParameters: ApiProjectsReorderCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProjectsReorderCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiProjectsRetrieve without sending the request
     */
    async apiProjectsRetrieveRequestOpts(requestParameters: ApiProjectsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve Project
     */
    async apiProjectsRetrieveRaw(requestParameters: ApiProjectsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSchema>> {
        const requestOptions = await this.apiProjectsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve Project
     */
    async apiProjectsRetrieve(requestParameters: ApiProjectsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSchema> {
        const response = await this.apiProjectsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksCountRetrieve without sending the request
     */
    async apiTasksCountRetrieveRequestOpts(requestParameters: ApiTasksCountRetrieveRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/count/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Count Tasks
     */
    async apiTasksCountRetrieveRaw(requestParameters: ApiTasksCountRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskCountSchema>> {
        const requestOptions = await this.apiTasksCountRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskCountSchemaFromJSON(jsonValue));
    }

    /**
     * Count Tasks
     */
    async apiTasksCountRetrieve(requestParameters: ApiTasksCountRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskCountSchema> {
        const response = await this.apiTasksCountRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksCreate without sending the request
     */
    async apiTasksCreateRequestOpts(requestParameters: ApiTasksCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['todoCreateInput'] == null) {
            throw new runtime.RequiredError(
                'todoCreateInput',
                'Required parameter "todoCreateInput" was null or undefined when calling apiTasksCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoCreateInputToJSON(requestParameters['todoCreateInput']),
        };
    }

    /**
     * Create Task
     */
    async apiTasksCreateRaw(requestParameters: ApiTasksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoSchema>> {
        const requestOptions = await this.apiTasksCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }

    /**
     * Create Task
     */
    async apiTasksCreate(requestParameters: ApiTasksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoSchema> {
        const response = await this.apiTasksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksDestroy without sending the request
     */
    async apiTasksDestroyRequestOpts(requestParameters: ApiTasksDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Task
     */
    async apiTasksDestroyRaw(requestParameters: ApiTasksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTasksDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Task
     */
    async apiTasksDestroy(requestParameters: ApiTasksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTasksDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiTasksList without sending the request
     */
    async apiTasksListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Tasks
     */
    async apiTasksListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoSchema>>> {
        const requestOptions = await this.apiTasksListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoSchemaFromJSON));
    }

    /**
     * List Tasks
     */
    async apiTasksList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoSchema>> {
        const response = await this.apiTasksListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksOpenList without sending the request
     */
    async apiTasksOpenListRequestOpts(requestParameters: ApiTasksOpenListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/open/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Open Tasks
     */
    async apiTasksOpenListRaw(requestParameters: ApiTasksOpenListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoSchema>>> {
        const requestOptions = await this.apiTasksOpenListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoSchemaFromJSON));
    }

    /**
     * Open Tasks
     */
    async apiTasksOpenList(requestParameters: ApiTasksOpenListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoSchema>> {
        const response = await this.apiTasksOpenListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksPartialUpdate without sending the request
     */
    async apiTasksPartialUpdateRequestOpts(requestParameters: ApiTasksPartialUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksPartialUpdate().'
            );
        }

        if (requestParameters['todoUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'todoUpdateInput',
                'Required parameter "todoUpdateInput" was null or undefined when calling apiTasksPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TodoUpdateInputToJSON(requestParameters['todoUpdateInput']),
        };
    }

    /**
     * Update Task
     */
    async apiTasksPartialUpdateRaw(requestParameters: ApiTasksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoSchema>> {
        const requestOptions = await this.apiTasksPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }

    /**
     * Update Task
     */
    async apiTasksPartialUpdate(requestParameters: ApiTasksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoSchema> {
        const response = await this.apiTasksPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksReorderCreate without sending the request
     */
    async apiTasksReorderCreateRequestOpts(requestParameters: ApiTasksReorderCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reorderInput'] == null) {
            throw new runtime.RequiredError(
                'reorderInput',
                'Required parameter "reorderInput" was null or undefined when calling apiTasksReorderCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/reorder/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderInputToJSON(requestParameters['reorderInput']),
        };
    }

    /**
     * Reorder Tasks
     */
    async apiTasksReorderCreateRaw(requestParameters: ApiTasksReorderCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTasksReorderCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reorder Tasks
     */
    async apiTasksReorderCreate(requestParameters: ApiTasksReorderCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTasksReorderCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiTasksRetrieve without sending the request
     */
    async apiTasksRetrieveRequestOpts(requestParameters: ApiTasksRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve Task
     */
    async apiTasksRetrieveRaw(requestParameters: ApiTasksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoSchema>> {
        const requestOptions = await this.apiTasksRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve Task
     */
    async apiTasksRetrieve(requestParameters: ApiTasksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoSchema> {
        const response = await this.apiTasksRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksViewList without sending the request
     */
    async apiTasksViewListRequestOpts(requestParameters: ApiTasksViewListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['view'] != null) {
            queryParameters['view'] = requestParameters['view'];
        }

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/view/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * View Tasks
     */
    async apiTasksViewListRaw(requestParameters: ApiTasksViewListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoSchema>>> {
        const requestOptions = await this.apiTasksViewListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoSchemaFromJSON));
    }

    /**
     * View Tasks
     */
    async apiTasksViewList(requestParameters: ApiTasksViewListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoSchema>> {
        const response = await this.apiTasksViewListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTokenCreate without sending the request
     */
    async apiTokenCreateRequestOpts(requestParameters: ApiTokenCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenObtainPair'] == null) {
            throw new runtime.RequiredError(
                'tokenObtainPair',
                'Required parameter "tokenObtainPair" was null or undefined when calling apiTokenCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/token/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenObtainPairToJSON(requestParameters['tokenObtainPair']),
        };
    }

    /**
     * Obtain Token
     */
    async apiTokenCreateRaw(requestParameters: ApiTokenCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPair>> {
        const requestOptions = await this.apiTokenCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPairFromJSON(jsonValue));
    }

    /**
     * Obtain Token
     */
    async apiTokenCreate(requestParameters: ApiTokenCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPair> {
        const response = await this.apiTokenCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTokenRefreshCreate without sending the request
     */
    async apiTokenRefreshCreateRequestOpts(requestParameters: ApiTokenRefreshCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenRefresh'] == null) {
            throw new runtime.RequiredError(
                'tokenRefresh',
                'Required parameter "tokenRefresh" was null or undefined when calling apiTokenRefreshCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/token/refresh/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshToJSON(requestParameters['tokenRefresh']),
        };
    }

    /**
     * Refresh Token
     */
    async apiTokenRefreshCreateRaw(requestParameters: ApiTokenRefreshCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessToken>> {
        const requestOptions = await this.apiTokenRefreshCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenFromJSON(jsonValue));
    }

    /**
     * Refresh Token
     */
    async apiTokenRefreshCreate(requestParameters: ApiTokenRefreshCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessToken> {
        const response = await this.apiTokenRefreshCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
