/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccessToken,
    AccessTokenFromJSON,
    AccessTokenToJSON,
} from '../models/AccessToken';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type TokenObtainPair,
    TokenObtainPairFromJSON,
    TokenObtainPairToJSON,
} from '../models/TokenObtainPair';
import {
    type TokenPair,
    TokenPairFromJSON,
    TokenPairToJSON,
} from '../models/TokenPair';
import {
    type TokenRefresh,
    TokenRefreshFromJSON,
    TokenRefreshToJSON,
} from '../models/TokenRefresh';

export interface ApiTokenCreateRequest {
    tokenObtainPair: TokenObtainPair;
}

export interface ApiTokenRefreshCreateRequest {
    tokenRefresh: TokenRefresh;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiTokenCreate without sending the request
     */
    async apiTokenCreateRequestOpts(requestParameters: ApiTokenCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenObtainPair'] == null) {
            throw new runtime.RequiredError(
                'tokenObtainPair',
                'Required parameter "tokenObtainPair" was null or undefined when calling apiTokenCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/token/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenObtainPairToJSON(requestParameters['tokenObtainPair']),
        };
    }

    /**
     * Obtain Token
     */
    async apiTokenCreateRaw(requestParameters: ApiTokenCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPair>> {
        const requestOptions = await this.apiTokenCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPairFromJSON(jsonValue));
    }

    /**
     * Obtain Token
     */
    async apiTokenCreate(requestParameters: ApiTokenCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPair> {
        const response = await this.apiTokenCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTokenRefreshCreate without sending the request
     */
    async apiTokenRefreshCreateRequestOpts(requestParameters: ApiTokenRefreshCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenRefresh'] == null) {
            throw new runtime.RequiredError(
                'tokenRefresh',
                'Required parameter "tokenRefresh" was null or undefined when calling apiTokenRefreshCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/token/refresh/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshToJSON(requestParameters['tokenRefresh']),
        };
    }

    /**
     * Refresh Token
     */
    async apiTokenRefreshCreateRaw(requestParameters: ApiTokenRefreshCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessToken>> {
        const requestOptions = await this.apiTokenRefreshCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenFromJSON(jsonValue));
    }

    /**
     * Refresh Token
     */
    async apiTokenRefreshCreate(requestParameters: ApiTokenRefreshCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessToken> {
        const response = await this.apiTokenRefreshCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
