/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type ChatRequest,
  ChatRequestFromJSON,
  ChatRequestToJSON,
} from "../models/ChatRequest";
import {
  type HTTPValidationError,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
} from "../models/HTTPValidationError";

export interface ApiChatCreateRequest {
  workspaceId: number;
  chatRequest: ChatRequest;
}

/**
 *
 */
export class ChatApi extends runtime.BaseAPI {
  /**
   * Creates request options for apiChatCreate without sending the request
   */
  async apiChatCreateRequestOpts(
    requestParameters: ApiChatCreateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiChatCreate().',
      );
    }

    if (requestParameters["chatRequest"] == null) {
      throw new runtime.RequiredError(
        "chatRequest",
        'Required parameter "chatRequest" was null or undefined when calling apiChatCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/chat/`;
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ChatRequestToJSON(requestParameters["chatRequest"]),
    };
  }

  /**
   * Chat with the local model, streaming tokens and tool activity as SSE.  The conversation is replayed by the client on each turn. Authorization is the normal workspace-membership check; the caller\'s token is forwarded to the MCP server so the model\'s tool calls run as that user.
   * Chat
   */
  async apiChatCreateRaw(
    requestParameters: ApiChatCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.apiChatCreateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Chat with the local model, streaming tokens and tool activity as SSE.  The conversation is replayed by the client on each turn. Authorization is the normal workspace-membership check; the caller\'s token is forwarded to the MCP server so the model\'s tool calls run as that user.
   * Chat
   */
  async apiChatCreate(
    requestParameters: ApiChatCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiChatCreateRaw(requestParameters, initOverrides);
  }
}
