/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommentCreateInput,
    CommentCreateInputFromJSON,
    CommentCreateInputToJSON,
} from '../models/CommentCreateInput';
import {
    type CommentSchema,
    CommentSchemaFromJSON,
    CommentSchemaToJSON,
} from '../models/CommentSchema';
import {
    type CommentUpdateInput,
    CommentUpdateInputFromJSON,
    CommentUpdateInputToJSON,
} from '../models/CommentUpdateInput';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface ApiTaskCommentsCreateRequest {
    taskId: number;
    commentCreateInput: CommentCreateInput;
}

export interface ApiTaskCommentsDestroyRequest {
    taskId: number;
    commentId: number;
}

export interface ApiTaskCommentsListRequest {
    taskId: number;
}

export interface ApiTaskCommentsPartialUpdateRequest {
    taskId: number;
    commentId: number;
    commentUpdateInput: CommentUpdateInput;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiTaskCommentsCreate without sending the request
     */
    async apiTaskCommentsCreateRequestOpts(requestParameters: ApiTaskCommentsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling apiTaskCommentsCreate().'
            );
        }

        if (requestParameters['commentCreateInput'] == null) {
            throw new runtime.RequiredError(
                'commentCreateInput',
                'Required parameter "commentCreateInput" was null or undefined when calling apiTaskCommentsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{task_id}/comments/`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentCreateInputToJSON(requestParameters['commentCreateInput']),
        };
    }

    /**
     * Create Comment
     */
    async apiTaskCommentsCreateRaw(requestParameters: ApiTaskCommentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentSchema>> {
        const requestOptions = await this.apiTaskCommentsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentSchemaFromJSON(jsonValue));
    }

    /**
     * Create Comment
     */
    async apiTaskCommentsCreate(requestParameters: ApiTaskCommentsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentSchema> {
        const response = await this.apiTaskCommentsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTaskCommentsDestroy without sending the request
     */
    async apiTaskCommentsDestroyRequestOpts(requestParameters: ApiTaskCommentsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling apiTaskCommentsDestroy().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling apiTaskCommentsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{task_id}/comments/{comment_id}/`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));
        urlPath = urlPath.replace('{comment_id}', encodeURIComponent(String(requestParameters['commentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Comment
     */
    async apiTaskCommentsDestroyRaw(requestParameters: ApiTaskCommentsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTaskCommentsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Comment
     */
    async apiTaskCommentsDestroy(requestParameters: ApiTaskCommentsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTaskCommentsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiTaskCommentsList without sending the request
     */
    async apiTaskCommentsListRequestOpts(requestParameters: ApiTaskCommentsListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling apiTaskCommentsList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{task_id}/comments/`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Comments
     */
    async apiTaskCommentsListRaw(requestParameters: ApiTaskCommentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentSchema>>> {
        const requestOptions = await this.apiTaskCommentsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentSchemaFromJSON));
    }

    /**
     * List Comments
     */
    async apiTaskCommentsList(requestParameters: ApiTaskCommentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentSchema>> {
        const response = await this.apiTaskCommentsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTaskCommentsPartialUpdate without sending the request
     */
    async apiTaskCommentsPartialUpdateRequestOpts(requestParameters: ApiTaskCommentsPartialUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling apiTaskCommentsPartialUpdate().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling apiTaskCommentsPartialUpdate().'
            );
        }

        if (requestParameters['commentUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'commentUpdateInput',
                'Required parameter "commentUpdateInput" was null or undefined when calling apiTaskCommentsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/tasks/{task_id}/comments/{comment_id}/`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));
        urlPath = urlPath.replace('{comment_id}', encodeURIComponent(String(requestParameters['commentId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CommentUpdateInputToJSON(requestParameters['commentUpdateInput']),
        };
    }

    /**
     * Update Comment
     */
    async apiTaskCommentsPartialUpdateRaw(requestParameters: ApiTaskCommentsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentSchema>> {
        const requestOptions = await this.apiTaskCommentsPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentSchemaFromJSON(jsonValue));
    }

    /**
     * Update Comment
     */
    async apiTaskCommentsPartialUpdate(requestParameters: ApiTaskCommentsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentSchema> {
        const response = await this.apiTaskCommentsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
