/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type HTTPValidationError,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
} from "../models/HTTPValidationError";
import {
  type TaskCountSchema,
  TaskCountSchemaFromJSON,
  TaskCountSchemaToJSON,
} from "../models/TaskCountSchema";
import {
  type TaskCreateInput,
  TaskCreateInputFromJSON,
  TaskCreateInputToJSON,
} from "../models/TaskCreateInput";
import {
  type TaskMoveInput,
  TaskMoveInputFromJSON,
  TaskMoveInputToJSON,
} from "../models/TaskMoveInput";
import {
  type TaskSchema,
  TaskSchemaFromJSON,
  TaskSchemaToJSON,
} from "../models/TaskSchema";
import {
  type TaskStatus,
  TaskStatusFromJSON,
  TaskStatusToJSON,
} from "../models/TaskStatus";
import {
  type TaskUpdateInput,
  TaskUpdateInputFromJSON,
  TaskUpdateInputToJSON,
} from "../models/TaskUpdateInput";

export interface ApiTasksCountRetrieveRequest {
  workspaceId: number;
  status?: TaskStatus | null;
}

export interface ApiTasksCreateRequest {
  workspaceId: number;
  taskCreateInput: TaskCreateInput;
}

export interface ApiTasksDestroyRequest {
  id: number;
  workspaceId: number;
}

export interface ApiTasksListRequest {
  workspaceId: number;
}

export interface ApiTasksMoveCreateRequest {
  id: number;
  workspaceId: number;
  taskMoveInput: TaskMoveInput;
}

export interface ApiTasksOpenListRequest {
  workspaceId: number;
  limit?: number | null;
}

export interface ApiTasksPartialUpdateRequest {
  id: number;
  workspaceId: number;
  taskUpdateInput: TaskUpdateInput;
}

export interface ApiTasksRetrieveRequest {
  id: number;
  workspaceId: number;
}

export interface ApiTasksViewListRequest {
  workspaceId: number;
  view?: ApiTasksViewListViewEnum;
  project?: number | null;
  tz?: string;
}

/**
 *
 */
export class TasksApi extends runtime.BaseAPI {
  /**
   * Creates request options for apiTasksCountRetrieve without sending the request
   */
  async apiTasksCountRetrieveRequestOpts(
    requestParameters: ApiTasksCountRetrieveRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksCountRetrieve().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/count/`;
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Count Tasks
   */
  async apiTasksCountRetrieveRaw(
    requestParameters: ApiTasksCountRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskCountSchema>> {
    const requestOptions =
      await this.apiTasksCountRetrieveRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskCountSchemaFromJSON(jsonValue),
    );
  }

  /**
   * Count Tasks
   */
  async apiTasksCountRetrieve(
    requestParameters: ApiTasksCountRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskCountSchema> {
    const response = await this.apiTasksCountRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiTasksCreate without sending the request
   */
  async apiTasksCreateRequestOpts(
    requestParameters: ApiTasksCreateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksCreate().',
      );
    }

    if (requestParameters["taskCreateInput"] == null) {
      throw new runtime.RequiredError(
        "taskCreateInput",
        'Required parameter "taskCreateInput" was null or undefined when calling apiTasksCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/`;
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: TaskCreateInputToJSON(requestParameters["taskCreateInput"]),
    };
  }

  /**
   * Create Task
   */
  async apiTasksCreateRaw(
    requestParameters: ApiTasksCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskSchema>> {
    const requestOptions =
      await this.apiTasksCreateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskSchemaFromJSON(jsonValue),
    );
  }

  /**
   * Create Task
   */
  async apiTasksCreate(
    requestParameters: ApiTasksCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskSchema> {
    const response = await this.apiTasksCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiTasksDestroy without sending the request
   */
  async apiTasksDestroyRequestOpts(
    requestParameters: ApiTasksDestroyRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiTasksDestroy().',
      );
    }

    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksDestroy().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/{id}/`;
    urlPath = urlPath.replace(
      "{id}",
      encodeURIComponent(String(requestParameters["id"])),
    );
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete Task
   */
  async apiTasksDestroyRaw(
    requestParameters: ApiTasksDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.apiTasksDestroyRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete Task
   */
  async apiTasksDestroy(
    requestParameters: ApiTasksDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiTasksDestroyRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for apiTasksList without sending the request
   */
  async apiTasksListRequestOpts(
    requestParameters: ApiTasksListRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksList().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/`;
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * List Tasks
   */
  async apiTasksListRaw(
    requestParameters: ApiTasksListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TaskSchema>>> {
    const requestOptions =
      await this.apiTasksListRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TaskSchemaFromJSON),
    );
  }

  /**
   * List Tasks
   */
  async apiTasksList(
    requestParameters: ApiTasksListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TaskSchema>> {
    const response = await this.apiTasksListRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiTasksMoveCreate without sending the request
   */
  async apiTasksMoveCreateRequestOpts(
    requestParameters: ApiTasksMoveCreateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiTasksMoveCreate().',
      );
    }

    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksMoveCreate().',
      );
    }

    if (requestParameters["taskMoveInput"] == null) {
      throw new runtime.RequiredError(
        "taskMoveInput",
        'Required parameter "taskMoveInput" was null or undefined when calling apiTasksMoveCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/{id}/move/`;
    urlPath = urlPath.replace(
      "{id}",
      encodeURIComponent(String(requestParameters["id"])),
    );
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: TaskMoveInputToJSON(requestParameters["taskMoveInput"]),
    };
  }

  /**
   * Move Task
   */
  async apiTasksMoveCreateRaw(
    requestParameters: ApiTasksMoveCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.apiTasksMoveCreateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Move Task
   */
  async apiTasksMoveCreate(
    requestParameters: ApiTasksMoveCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiTasksMoveCreateRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for apiTasksOpenList without sending the request
   */
  async apiTasksOpenListRequestOpts(
    requestParameters: ApiTasksOpenListRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksOpenList().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/open/`;
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Open Tasks
   */
  async apiTasksOpenListRaw(
    requestParameters: ApiTasksOpenListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TaskSchema>>> {
    const requestOptions =
      await this.apiTasksOpenListRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TaskSchemaFromJSON),
    );
  }

  /**
   * Open Tasks
   */
  async apiTasksOpenList(
    requestParameters: ApiTasksOpenListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TaskSchema>> {
    const response = await this.apiTasksOpenListRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiTasksPartialUpdate without sending the request
   */
  async apiTasksPartialUpdateRequestOpts(
    requestParameters: ApiTasksPartialUpdateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiTasksPartialUpdate().',
      );
    }

    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksPartialUpdate().',
      );
    }

    if (requestParameters["taskUpdateInput"] == null) {
      throw new runtime.RequiredError(
        "taskUpdateInput",
        'Required parameter "taskUpdateInput" was null or undefined when calling apiTasksPartialUpdate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/{id}/`;
    urlPath = urlPath.replace(
      "{id}",
      encodeURIComponent(String(requestParameters["id"])),
    );
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: TaskUpdateInputToJSON(requestParameters["taskUpdateInput"]),
    };
  }

  /**
   * Update Task
   */
  async apiTasksPartialUpdateRaw(
    requestParameters: ApiTasksPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskSchema>> {
    const requestOptions =
      await this.apiTasksPartialUpdateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskSchemaFromJSON(jsonValue),
    );
  }

  /**
   * Update Task
   */
  async apiTasksPartialUpdate(
    requestParameters: ApiTasksPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskSchema> {
    const response = await this.apiTasksPartialUpdateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiTasksRetrieve without sending the request
   */
  async apiTasksRetrieveRequestOpts(
    requestParameters: ApiTasksRetrieveRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiTasksRetrieve().',
      );
    }

    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksRetrieve().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/{id}/`;
    urlPath = urlPath.replace(
      "{id}",
      encodeURIComponent(String(requestParameters["id"])),
    );
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieve Task
   */
  async apiTasksRetrieveRaw(
    requestParameters: ApiTasksRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TaskSchema>> {
    const requestOptions =
      await this.apiTasksRetrieveRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TaskSchemaFromJSON(jsonValue),
    );
  }

  /**
   * Retrieve Task
   */
  async apiTasksRetrieve(
    requestParameters: ApiTasksRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TaskSchema> {
    const response = await this.apiTasksRetrieveRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiTasksViewList without sending the request
   */
  async apiTasksViewListRequestOpts(
    requestParameters: ApiTasksViewListRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceId"] == null) {
      throw new runtime.RequiredError(
        "workspaceId",
        'Required parameter "workspaceId" was null or undefined when calling apiTasksViewList().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["view"] != null) {
      queryParameters["view"] = requestParameters["view"];
    }

    if (requestParameters["project"] != null) {
      queryParameters["project"] = requestParameters["project"];
    }

    if (requestParameters["tz"] != null) {
      queryParameters["tz"] = requestParameters["tz"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/{workspace_id}/tasks/view/`;
    urlPath = urlPath.replace(
      "{workspace_id}",
      encodeURIComponent(String(requestParameters["workspaceId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * View Tasks
   */
  async apiTasksViewListRaw(
    requestParameters: ApiTasksViewListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TaskSchema>>> {
    const requestOptions =
      await this.apiTasksViewListRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TaskSchemaFromJSON),
    );
  }

  /**
   * View Tasks
   */
  async apiTasksViewList(
    requestParameters: ApiTasksViewListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TaskSchema>> {
    const response = await this.apiTasksViewListRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}

/**
 * @export
 */
export const ApiTasksViewListViewEnum = {
  Inbox: "inbox",
  Today: "today",
  Upcoming: "upcoming",
  All: "all",
} as const;
export type ApiTasksViewListViewEnum =
  (typeof ApiTasksViewListViewEnum)[keyof typeof ApiTasksViewListViewEnum];
