/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type HTTPValidationError,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
} from "../models/HTTPValidationError";
import {
  type WorkspaceCreateInput,
  WorkspaceCreateInputFromJSON,
  WorkspaceCreateInputToJSON,
} from "../models/WorkspaceCreateInput";
import {
  type WorkspaceSchema,
  WorkspaceSchemaFromJSON,
  WorkspaceSchemaToJSON,
} from "../models/WorkspaceSchema";

export interface ApiWorkspacesCreateRequest {
  workspaceCreateInput: WorkspaceCreateInput;
}

/**
 *
 */
export class WorkspacesApi extends runtime.BaseAPI {
  /**
   * Creates request options for apiWorkspacesCreate without sending the request
   */
  async apiWorkspacesCreateRequestOpts(
    requestParameters: ApiWorkspacesCreateRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["workspaceCreateInput"] == null) {
      throw new runtime.RequiredError(
        "workspaceCreateInput",
        'Required parameter "workspaceCreateInput" was null or undefined when calling apiWorkspacesCreate().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: WorkspaceCreateInputToJSON(
        requestParameters["workspaceCreateInput"],
      ),
    };
  }

  /**
   * Create Workspace
   */
  async apiWorkspacesCreateRaw(
    requestParameters: ApiWorkspacesCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WorkspaceSchema>> {
    const requestOptions =
      await this.apiWorkspacesCreateRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      WorkspaceSchemaFromJSON(jsonValue),
    );
  }

  /**
   * Create Workspace
   */
  async apiWorkspacesCreate(
    requestParameters: ApiWorkspacesCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WorkspaceSchema> {
    const response = await this.apiWorkspacesCreateRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for apiWorkspacesList without sending the request
   */
  async apiWorkspacesListRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/workspaces/`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * List Workspaces
   */
  async apiWorkspacesListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<WorkspaceSchema>>> {
    const requestOptions = await this.apiWorkspacesListRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(WorkspaceSchemaFromJSON),
    );
  }

  /**
   * List Workspaces
   */
  async apiWorkspacesList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<WorkspaceSchema>> {
    const response = await this.apiWorkspacesListRaw(initOverrides);
    return await response.value();
  }
}
