/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the AccessToken interface.
 */
export function instanceOfAccessToken(value) {
    if (!('access' in value) || value['access'] === undefined)
        return false;
    return true;
}
export function AccessTokenFromJSON(json) {
    return AccessTokenFromJSONTyped(json, false);
}
export function AccessTokenFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'access': json['access'],
    };
}
export function AccessTokenToJSON(json) {
    return AccessTokenToJSONTyped(json, false);
}
export function AccessTokenToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'access': value['access'],
    };
}
