/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
  /**
   *
   * @type {string}
   * @memberof AccessToken
   */
  access: string;
}

/**
 * Check if a given object implements the AccessToken interface.
 */
export function instanceOfAccessToken(value: object): value is AccessToken {
  if (!("access" in value) || value["access"] === undefined) return false;
  return true;
}

export function AccessTokenFromJSON(json: any): AccessToken {
  return AccessTokenFromJSONTyped(json, false);
}

export function AccessTokenFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AccessToken {
  if (json == null) {
    return json;
  }
  return {
    access: json["access"],
  };
}

export function AccessTokenToJSON(json: any): AccessToken {
  return AccessTokenToJSONTyped(json, false);
}

export function AccessTokenToJSONTyped(
  value?: AccessToken | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    access: value["access"],
  };
}
