/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ChatMessageInput } from "./ChatMessageInput";
import {
  ChatMessageInputFromJSON,
  ChatMessageInputFromJSONTyped,
  ChatMessageInputToJSON,
  ChatMessageInputToJSONTyped,
} from "./ChatMessageInput";

/**
 *
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
  /**
   *
   * @type {Array<ChatMessageInput>}
   * @memberof ChatRequest
   */
  messages: Array<ChatMessageInput>;
}

/**
 * Check if a given object implements the ChatRequest interface.
 */
export function instanceOfChatRequest(value: object): value is ChatRequest {
  if (!("messages" in value) || value["messages"] === undefined) return false;
  return true;
}

export function ChatRequestFromJSON(json: any): ChatRequest {
  return ChatRequestFromJSONTyped(json, false);
}

export function ChatRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatRequest {
  if (json == null) {
    return json;
  }
  return {
    messages: (json["messages"] as Array<any>).map(ChatMessageInputFromJSON),
  };
}

export function ChatRequestToJSON(json: any): ChatRequest {
  return ChatRequestToJSONTyped(json, false);
}

export function ChatRequestToJSONTyped(
  value?: ChatRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    messages: (value["messages"] as Array<any>).map(ChatMessageInputToJSON),
  };
}
