/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentCreateInput
 */
export interface CommentCreateInput {
    /**
     * 
     * @type {string}
     * @memberof CommentCreateInput
     */
    body: string;
}

/**
 * Check if a given object implements the CommentCreateInput interface.
 */
export function instanceOfCommentCreateInput(value: object): value is CommentCreateInput {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CommentCreateInputFromJSON(json: any): CommentCreateInput {
    return CommentCreateInputFromJSONTyped(json, false);
}

export function CommentCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function CommentCreateInputToJSON(json: any): CommentCreateInput {
    return CommentCreateInputToJSONTyped(json, false);
}

export function CommentCreateInputToJSONTyped(value?: CommentCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

