/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentSchema
 */
export interface CommentSchema {
    /**
     * 
     * @type {number}
     * @memberof CommentSchema
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof CommentSchema
     */
    taskId: number;
    /**
     * 
     * @type {string}
     * @memberof CommentSchema
     */
    body: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentSchema
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommentSchema
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the CommentSchema interface.
 */
export function instanceOfCommentSchema(value: object): value is CommentSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('taskId' in (value as Record<string, any>)) && !('task_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['taskId'] === undefined && (value as Record<string, any>)['task_id'] === undefined)) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function CommentSchemaFromJSON(json: any): CommentSchema {
    return CommentSchemaFromJSONTyped(json, false);
}

export function CommentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'taskId': json['task_id'],
        'body': json['body'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CommentSchemaToJSON(json: any): CommentSchema {
    return CommentSchemaToJSONTyped(json, false);
}

export function CommentSchemaToJSONTyped(value?: CommentSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'task_id': value['taskId'],
        'body': value['body'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

