/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentUpdateInput
 */
export interface CommentUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof CommentUpdateInput
     */
    body: string;
}

/**
 * Check if a given object implements the CommentUpdateInput interface.
 */
export function instanceOfCommentUpdateInput(value: object): value is CommentUpdateInput {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CommentUpdateInputFromJSON(json: any): CommentUpdateInput {
    return CommentUpdateInputFromJSONTyped(json, false);
}

export function CommentUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function CommentUpdateInputToJSON(json: any): CommentUpdateInput {
    return CommentUpdateInputToJSONTyped(json, false);
}

export function CommentUpdateInputToJSONTyped(value?: CommentUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

