/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentTime
 */
export interface CurrentTime {
    /**
     * 
     * @type {Date}
     * @memberof CurrentTime
     */
    currentTime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CurrentTime
     */
    cached: boolean;
}

/**
 * Check if a given object implements the CurrentTime interface.
 */
export function instanceOfCurrentTime(value: object): value is CurrentTime {
    if ((!('currentTime' in (value as Record<string, any>)) && !('current_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentTime'] === undefined && (value as Record<string, any>)['current_time'] === undefined)) return false;
    if (!('cached' in value) || value['cached'] === undefined) return false;
    return true;
}

export function CurrentTimeFromJSON(json: any): CurrentTime {
    return CurrentTimeFromJSONTyped(json, false);
}

export function CurrentTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentTime {
    if (json == null) {
        return json;
    }
    return {
        
        'currentTime': (new Date(json['current_time'])),
        'cached': json['cached'],
    };
}

export function CurrentTimeToJSON(json: any): CurrentTime {
    return CurrentTimeToJSONTyped(json, false);
}

export function CurrentTimeToJSONTyped(value?: CurrentTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_time': value['currentTime'].toISOString(),
        'cached': value['cached'],
    };
}

