/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the LocationInner interface.
 */
export function instanceOfLocationInner(value) {
    return true;
}
export function LocationInnerFromJSON(json) {
    return LocationInnerFromJSONTyped(json, false);
}
export function LocationInnerFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
export function LocationInnerToJSON(json) {
    return LocationInnerToJSONTyped(json, false);
}
export function LocationInnerToJSONTyped(value, ignoreDiscriminator = false) {
    return value;
}
