/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the ProjectUpdateInput interface.
 */
export function instanceOfProjectUpdateInput(value) {
    return true;
}
export function ProjectUpdateInputFromJSON(json) {
    return ProjectUpdateInputFromJSONTyped(json, false);
}
export function ProjectUpdateInputFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
    };
}
export function ProjectUpdateInputToJSON(json) {
    return ProjectUpdateInputToJSONTyped(json, false);
}
export function ProjectUpdateInputToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
    };
}
