/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StatusSchema } from "./StatusSchema";
import {
  StatusSchemaFromJSON,
  StatusSchemaFromJSONTyped,
  StatusSchemaToJSON,
  StatusSchemaToJSONTyped,
} from "./StatusSchema";

/**
 * One project, with the workflow its board renders as columns.
 *
 * Only the detail response carries it: the sidebar lists projects but never
 * draws their boards, so shipping every workflow there would be dead weight.
 * @export
 * @interface ProjectDetailSchema
 */
export interface ProjectDetailSchema {
  /**
   *
   * @type {Array<StatusSchema>}
   * @memberof ProjectDetailSchema
   */
  workflow: Array<StatusSchema>;
  /**
   *
   * @type {number}
   * @memberof ProjectDetailSchema
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ProjectDetailSchema
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ProjectDetailSchema
   */
  color?: string | null;
  /**
   *
   * @type {number}
   * @memberof ProjectDetailSchema
   */
  taskCount?: number;
  /**
   *
   * @type {Date}
   * @memberof ProjectDetailSchema
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ProjectDetailSchema
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the ProjectDetailSchema interface.
 */
export function instanceOfProjectDetailSchema(
  value: object,
): value is ProjectDetailSchema {
  if (!("workflow" in value) || value["workflow"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (
    (!("createdAt" in (value as Record<string, any>)) &&
      !("created_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["createdAt"] === undefined &&
      (value as Record<string, any>)["created_at"] === undefined)
  )
    return false;
  if (
    (!("updatedAt" in (value as Record<string, any>)) &&
      !("updated_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["updatedAt"] === undefined &&
      (value as Record<string, any>)["updated_at"] === undefined)
  )
    return false;
  return true;
}

export function ProjectDetailSchemaFromJSON(json: any): ProjectDetailSchema {
  return ProjectDetailSchemaFromJSONTyped(json, false);
}

export function ProjectDetailSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectDetailSchema {
  if (json == null) {
    return json;
  }
  return {
    workflow: (json["workflow"] as Array<any>).map(StatusSchemaFromJSON),
    id: json["id"],
    name: json["name"],
    color:
      json["color"] === undefined
        ? undefined
        : json["color"] === null
          ? null
          : json["color"],
    taskCount: json["task_count"] == null ? undefined : json["task_count"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function ProjectDetailSchemaToJSON(json: any): ProjectDetailSchema {
  return ProjectDetailSchemaToJSONTyped(json, false);
}

export function ProjectDetailSchemaToJSONTyped(
  value?: ProjectDetailSchema | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    workflow: (value["workflow"] as Array<any>).map(StatusSchemaToJSON),
    id: value["id"],
    name: value["name"],
    color: value["color"],
    task_count: value["taskCount"],
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
  };
}
