/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the ProjectSchema interface.
 */
export function instanceOfProjectSchema(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined))
        return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined))
        return false;
    return true;
}
export function ProjectSchemaFromJSON(json) {
    return ProjectSchemaFromJSONTyped(json, false);
}
export function ProjectSchemaFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'taskCount': json['task_count'] == null ? undefined : json['task_count'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}
export function ProjectSchemaToJSON(json) {
    return ProjectSchemaToJSONTyped(json, false);
}
export function ProjectSchemaToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'task_count': value['taskCount'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}
