/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProjectCreateInput
 */
export interface ProjectCreateInput {
  /**
   *
   * @type {string}
   * @memberof ProjectCreateInput
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ProjectCreateInput
   */
  color?: string | null;
}

/**
 * Check if a given object implements the ProjectCreateInput interface.
 */
export function instanceOfProjectCreateInput(
  value: object,
): value is ProjectCreateInput {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function ProjectCreateInputFromJSON(json: any): ProjectCreateInput {
  return ProjectCreateInputFromJSONTyped(json, false);
}

export function ProjectCreateInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectCreateInput {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    color:
      json["color"] === undefined
        ? undefined
        : json["color"] === null
          ? null
          : json["color"],
  };
}

export function ProjectCreateInputToJSON(json: any): ProjectCreateInput {
  return ProjectCreateInputToJSONTyped(json, false);
}

export function ProjectCreateInputToJSONTyped(
  value?: ProjectCreateInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    color: value["color"],
  };
}
