/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the ReorderInput interface.
 */
export function instanceOfReorderInput(value) {
    if (!('order' in value) || value['order'] === undefined)
        return false;
    return true;
}
export function ReorderInputFromJSON(json) {
    return ReorderInputFromJSONTyped(json, false);
}
export function ReorderInputFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'order': json['order'],
    };
}
export function ReorderInputToJSON(json) {
    return ReorderInputToJSONTyped(json, false);
}
export function ReorderInputToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'order': value['order'],
    };
}
