/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReorderInput
 */
export interface ReorderInput {
  /**
   *
   * @type {Array<number>}
   * @memberof ReorderInput
   */
  order: Array<number>;
}

/**
 * Check if a given object implements the ReorderInput interface.
 */
export function instanceOfReorderInput(value: object): value is ReorderInput {
  if (!("order" in value) || value["order"] === undefined) return false;
  return true;
}

export function ReorderInputFromJSON(json: any): ReorderInput {
  return ReorderInputFromJSONTyped(json, false);
}

export function ReorderInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReorderInput {
  if (json == null) {
    return json;
  }
  return {
    order: json["order"],
  };
}

export function ReorderInputToJSON(json: any): ReorderInput {
  return ReorderInputToJSONTyped(json, false);
}

export function ReorderInputToJSONTyped(
  value?: ReorderInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    order: value["order"],
  };
}
