/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StatusSchema
 */
export interface StatusSchema {
  /**
   *
   * @type {string}
   * @memberof StatusSchema
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof StatusSchema
   */
  label: string;
  /**
   *
   * @type {boolean}
   * @memberof StatusSchema
   */
  isInitial: boolean;
  /**
   *
   * @type {boolean}
   * @memberof StatusSchema
   */
  isTerminal: boolean;
}

/**
 * Check if a given object implements the StatusSchema interface.
 */
export function instanceOfStatusSchema(value: object): value is StatusSchema {
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  if (
    (!("isInitial" in (value as Record<string, any>)) &&
      !("is_initial" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["isInitial"] === undefined &&
      (value as Record<string, any>)["is_initial"] === undefined)
  )
    return false;
  if (
    (!("isTerminal" in (value as Record<string, any>)) &&
      !("is_terminal" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["isTerminal"] === undefined &&
      (value as Record<string, any>)["is_terminal"] === undefined)
  )
    return false;
  return true;
}

export function StatusSchemaFromJSON(json: any): StatusSchema {
  return StatusSchemaFromJSONTyped(json, false);
}

export function StatusSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StatusSchema {
  if (json == null) {
    return json;
  }
  return {
    key: json["key"],
    label: json["label"],
    isInitial: json["is_initial"],
    isTerminal: json["is_terminal"],
  };
}

export function StatusSchemaToJSON(json: any): StatusSchema {
  return StatusSchemaToJSONTyped(json, false);
}

export function StatusSchemaToJSONTyped(
  value?: StatusSchema | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value["key"],
    label: value["label"],
    is_initial: value["isInitial"],
    is_terminal: value["isTerminal"],
  };
}
