/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StatusInput
 */
export interface StatusInput {
  /**
   *
   * @type {string}
   * @memberof StatusInput
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof StatusInput
   */
  label: string;
  /**
   *
   * @type {boolean}
   * @memberof StatusInput
   */
  isInitial?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof StatusInput
   */
  isTerminal?: boolean;
}

/**
 * Check if a given object implements the StatusInput interface.
 */
export function instanceOfStatusInput(value: object): value is StatusInput {
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  return true;
}

export function StatusInputFromJSON(json: any): StatusInput {
  return StatusInputFromJSONTyped(json, false);
}

export function StatusInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StatusInput {
  if (json == null) {
    return json;
  }
  return {
    key: json["key"],
    label: json["label"],
    isInitial: json["is_initial"] == null ? undefined : json["is_initial"],
    isTerminal: json["is_terminal"] == null ? undefined : json["is_terminal"],
  };
}

export function StatusInputToJSON(json: any): StatusInput {
  return StatusInputToJSONTyped(json, false);
}

export function StatusInputToJSONTyped(
  value?: StatusInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value["key"],
    label: value["label"],
    is_initial: value["isInitial"],
    is_terminal: value["isTerminal"],
  };
}
