/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TaskStatus } from "./TaskStatus";
import {
  TaskStatusFromJSON,
  TaskStatusFromJSONTyped,
  TaskStatusToJSON,
  TaskStatusToJSONTyped,
} from "./TaskStatus";

/**
 *
 * @export
 * @interface TaskSchema
 */
export interface TaskSchema {
  /**
   *
   * @type {number}
   * @memberof TaskSchema
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof TaskSchema
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof TaskSchema
   */
  description: string;
  /**
   *
   * @type {TaskStatus}
   * @memberof TaskSchema
   */
  status: TaskStatus;
  /**
   *
   * @type {number}
   * @memberof TaskSchema
   */
  position: number;
  /**
   *
   * @type {number}
   * @memberof TaskSchema
   */
  projectId: number | null;
  /**
   *
   * @type {Date}
   * @memberof TaskSchema
   */
  dueDate: Date | null;
  /**
   *
   * @type {Date}
   * @memberof TaskSchema
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof TaskSchema
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the TaskSchema interface.
 */
export function instanceOfTaskSchema(value: object): value is TaskSchema {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("position" in value) || value["position"] === undefined) return false;
  if (
    (!("projectId" in (value as Record<string, any>)) &&
      !("project_id" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["projectId"] === undefined &&
      (value as Record<string, any>)["project_id"] === undefined)
  )
    return false;
  if (
    (!("dueDate" in (value as Record<string, any>)) &&
      !("due_date" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["dueDate"] === undefined &&
      (value as Record<string, any>)["due_date"] === undefined)
  )
    return false;
  if (
    (!("createdAt" in (value as Record<string, any>)) &&
      !("created_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["createdAt"] === undefined &&
      (value as Record<string, any>)["created_at"] === undefined)
  )
    return false;
  if (
    (!("updatedAt" in (value as Record<string, any>)) &&
      !("updated_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["updatedAt"] === undefined &&
      (value as Record<string, any>)["updated_at"] === undefined)
  )
    return false;
  return true;
}

export function TaskSchemaFromJSON(json: any): TaskSchema {
  return TaskSchemaFromJSONTyped(json, false);
}

export function TaskSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaskSchema {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    description: json["description"],
    status: TaskStatusFromJSON(json["status"]),
    position: json["position"],
    projectId: json["project_id"],
    dueDate: json["due_date"] == null ? null : new Date(json["due_date"]),
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function TaskSchemaToJSON(json: any): TaskSchema {
  return TaskSchemaToJSONTyped(json, false);
}

export function TaskSchemaToJSONTyped(
  value?: TaskSchema | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    description: value["description"],
    status: TaskStatusToJSON(value["status"]),
    position: value["position"],
    project_id: value["projectId"],
    due_date:
      value["dueDate"] == null
        ? value["dueDate"]
        : value["dueDate"].toISOString().substring(0, 10),
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
  };
}
