/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatus } from './TaskStatus';
import {
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
    TaskStatusToJSONTyped,
} from './TaskStatus';

/**
 * 
 * @export
 * @interface TaskUpdateInput
 */
export interface TaskUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof TaskUpdateInput
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskUpdateInput
     */
    description?: string | null;
    /**
     * 
     * @type {TaskStatus}
     * @memberof TaskUpdateInput
     */
    status?: TaskStatus | null;
    /**
     * 
     * @type {number}
     * @memberof TaskUpdateInput
     */
    projectId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskUpdateInput
     */
    dueDate?: Date | null;
}



/**
 * Check if a given object implements the TaskUpdateInput interface.
 */
export function instanceOfTaskUpdateInput(value: object): value is TaskUpdateInput {
    return true;
}

export function TaskUpdateInputFromJSON(json: any): TaskUpdateInput {
    return TaskUpdateInputFromJSONTyped(json, false);
}

export function TaskUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] === undefined ? undefined : json['title'] === null ? null : json['title'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : TaskStatusFromJSON(json['status']),
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
        'dueDate': json['due_date'] === undefined ? undefined : json['due_date'] === null ? null : (new Date(json['due_date'])),
    };
}

export function TaskUpdateInputToJSON(json: any): TaskUpdateInput {
    return TaskUpdateInputToJSONTyped(json, false);
}

export function TaskUpdateInputToJSONTyped(value?: TaskUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': TaskStatusToJSON(value['status']),
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
    };
}

