/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatus } from './TaskStatus';
import {
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
    TaskStatusToJSONTyped,
} from './TaskStatus';

/**
 * 
 * @export
 * @interface TaskCreateInput
 */
export interface TaskCreateInput {
    /**
     * 
     * @type {string}
     * @memberof TaskCreateInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TaskCreateInput
     */
    description?: string;
    /**
     * 
     * @type {TaskStatus}
     * @memberof TaskCreateInput
     */
    status?: TaskStatus;
    /**
     * 
     * @type {number}
     * @memberof TaskCreateInput
     */
    projectId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskCreateInput
     */
    dueDate?: Date | null;
}



/**
 * Check if a given object implements the TaskCreateInput interface.
 */
export function instanceOfTaskCreateInput(value: object): value is TaskCreateInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TaskCreateInputFromJSON(json: any): TaskCreateInput {
    return TaskCreateInputFromJSONTyped(json, false);
}

export function TaskCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : TaskStatusFromJSON(json['status']),
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
        'dueDate': json['due_date'] === undefined ? undefined : json['due_date'] === null ? null : (new Date(json['due_date'])),
    };
}

export function TaskCreateInputToJSON(json: any): TaskCreateInput {
    return TaskCreateInputToJSONTyped(json, false);
}

export function TaskCreateInputToJSONTyped(value?: TaskCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'status': TaskStatusToJSON(value['status']),
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
    };
}

