/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TaskCountSchema
 */
export interface TaskCountSchema {
  /**
   *
   * @type {number}
   * @memberof TaskCountSchema
   */
  count: number;
}

/**
 * Check if a given object implements the TaskCountSchema interface.
 */
export function instanceOfTaskCountSchema(
  value: object,
): value is TaskCountSchema {
  if (!("count" in value) || value["count"] === undefined) return false;
  return true;
}

export function TaskCountSchemaFromJSON(json: any): TaskCountSchema {
  return TaskCountSchemaFromJSONTyped(json, false);
}

export function TaskCountSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaskCountSchema {
  if (json == null) {
    return json;
  }
  return {
    count: json["count"],
  };
}

export function TaskCountSchemaToJSON(json: any): TaskCountSchema {
  return TaskCountSchemaToJSONTyped(json, false);
}

export function TaskCountSchemaToJSONTyped(
  value?: TaskCountSchema | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
  };
}
