/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TaskMoveInput
 */
export interface TaskMoveInput {
  /**
   *
   * @type {string}
   * @memberof TaskMoveInput
   */
  status: string;
  /**
   *
   * @type {number}
   * @memberof TaskMoveInput
   */
  position: number;
}

/**
 * Check if a given object implements the TaskMoveInput interface.
 */
export function instanceOfTaskMoveInput(value: object): value is TaskMoveInput {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("position" in value) || value["position"] === undefined) return false;
  return true;
}

export function TaskMoveInputFromJSON(json: any): TaskMoveInput {
  return TaskMoveInputFromJSONTyped(json, false);
}

export function TaskMoveInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TaskMoveInput {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    position: json["position"],
  };
}

export function TaskMoveInputToJSON(json: any): TaskMoveInput {
  return TaskMoveInputToJSONTyped(json, false);
}

export function TaskMoveInputToJSONTyped(
  value?: TaskMoveInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    position: value["position"],
  };
}
