/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TodoSchema interface.
 */
export function instanceOfTodoSchema(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('completed' in value) || value['completed'] === undefined)
        return false;
    if ((!('projectId' in value) && !('project_id' in value)) || (value['projectId'] === undefined && value['project_id'] === undefined))
        return false;
    if ((!('dueDate' in value) && !('due_date' in value)) || (value['dueDate'] === undefined && value['due_date'] === undefined))
        return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined))
        return false;
    if ((!('updatedAt' in value) && !('updated_at' in value)) || (value['updatedAt'] === undefined && value['updated_at'] === undefined))
        return false;
    return true;
}
export function TodoSchemaFromJSON(json) {
    return TodoSchemaFromJSONTyped(json, false);
}
export function TodoSchemaFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'completed': json['completed'],
        'projectId': json['project_id'],
        'dueDate': (json['due_date'] == null ? null : new Date(json['due_date'])),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}
export function TodoSchemaToJSON(json) {
    return TodoSchemaToJSONTyped(json, false);
}
export function TodoSchemaToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'completed': value['completed'],
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0, 10),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}
