/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TodoProjectInput interface.
 */
export function instanceOfTodoProjectInput(value) {
    return true;
}
export function TodoProjectInputFromJSON(json) {
    return TodoProjectInputFromJSONTyped(json, false);
}
export function TodoProjectInputFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
    };
}
export function TodoProjectInputToJSON(json) {
    return TodoProjectInputToJSONTyped(json, false);
}
export function TodoProjectInputToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'project_id': value['projectId'],
    };
}
