/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenPair
 */
export interface TokenPair {
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    refresh: string;
}

/**
 * Check if a given object implements the TokenPair interface.
 */
export function instanceOfTokenPair(value: object): value is TokenPair {
    if (!('access' in value) || value['access'] === undefined) return false;
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    return true;
}

export function TokenPairFromJSON(json: any): TokenPair {
    return TokenPairFromJSONTyped(json, false);
}

export function TokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPair {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function TokenPairToJSON(json: any): TokenPair {
    return TokenPairToJSONTyped(json, false);
}

export function TokenPairToJSONTyped(value?: TokenPair | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access': value['access'],
        'refresh': value['refresh'],
    };
}

