/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TokenObtainPair interface.
 */
export function instanceOfTokenObtainPair(value) {
    if (!('username' in value) || value['username'] === undefined)
        return false;
    if (!('password' in value) || value['password'] === undefined)
        return false;
    if (!('access' in value) || value['access'] === undefined)
        return false;
    if (!('refresh' in value) || value['refresh'] === undefined)
        return false;
    return true;
}
export function TokenObtainPairFromJSON(json) {
    return TokenObtainPairFromJSONTyped(json, false);
}
export function TokenObtainPairFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'username': json['username'],
        'password': json['password'],
        'access': json['access'],
        'refresh': json['refresh'],
    };
}
export function TokenObtainPairToJSON(json) {
    return TokenObtainPairToJSONTyped(json, false);
}
export function TokenObtainPairToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'username': value['username'],
        'password': value['password'],
    };
}
