/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TokenRefresh interface.
 */
export function instanceOfTokenRefresh(value) {
    if (!('access' in value) || value['access'] === undefined)
        return false;
    if (!('refresh' in value) || value['refresh'] === undefined)
        return false;
    return true;
}
export function TokenRefreshFromJSON(json) {
    return TokenRefreshFromJSONTyped(json, false);
}
export function TokenRefreshFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'access': json['access'],
        'refresh': json['refresh'],
    };
}
export function TokenRefreshToJSON(json) {
    return TokenRefreshToJSONTyped(json, false);
}
export function TokenRefreshToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'refresh': value['refresh'],
    };
}
