/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserRegister
 */
export interface UserRegister {
  /**
   *
   * @type {string}
   * @memberof UserRegister
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UserRegister
   */
  password: string;
}

/**
 * Check if a given object implements the UserRegister interface.
 */
export function instanceOfUserRegister(value: object): value is UserRegister {
  if (!("username" in value) || value["username"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  return true;
}

export function UserRegisterFromJSON(json: any): UserRegister {
  return UserRegisterFromJSONTyped(json, false);
}

export function UserRegisterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserRegister {
  if (json == null) {
    return json;
  }
  return {
    username: json["username"],
    password: json["password"],
  };
}

export function UserRegisterToJSON(json: any): UserRegister {
  return UserRegisterToJSONTyped(json, false);
}

export function UserRegisterToJSONTyped(
  value?: UserRegister | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    username: value["username"],
    password: value["password"],
  };
}
