/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationInnerFromJSON, LocationInnerToJSON, } from './LocationInner';
/**
 * Check if a given object implements the ValidationError interface.
 */
export function instanceOfValidationError(value) {
    if (!('loc' in value) || value['loc'] === undefined)
        return false;
    if (!('msg' in value) || value['msg'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    return true;
}
export function ValidationErrorFromJSON(json) {
    return ValidationErrorFromJSONTyped(json, false);
}
export function ValidationErrorFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'loc': (json['loc'].map(LocationInnerFromJSON)),
        'msg': json['msg'],
        'type': json['type'],
        'input': json['input'] === undefined ? undefined : json['input'] === null ? null : json['input'],
        'ctx': json['ctx'] == null ? undefined : json['ctx'],
    };
}
export function ValidationErrorToJSON(json) {
    return ValidationErrorToJSONTyped(json, false);
}
export function ValidationErrorToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'loc': (value['loc'].map(LocationInnerToJSON)),
        'msg': value['msg'],
        'type': value['type'],
        'input': value['input'],
        'ctx': value['ctx'],
    };
}
