/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WorkspaceCreateInput
 */
export interface WorkspaceCreateInput {
  /**
   *
   * @type {string}
   * @memberof WorkspaceCreateInput
   */
  name: string;
}

/**
 * Check if a given object implements the WorkspaceCreateInput interface.
 */
export function instanceOfWorkspaceCreateInput(
  value: object,
): value is WorkspaceCreateInput {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function WorkspaceCreateInputFromJSON(json: any): WorkspaceCreateInput {
  return WorkspaceCreateInputFromJSONTyped(json, false);
}

export function WorkspaceCreateInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceCreateInput {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
  };
}

export function WorkspaceCreateInputToJSON(json: any): WorkspaceCreateInput {
  return WorkspaceCreateInputToJSONTyped(json, false);
}

export function WorkspaceCreateInputToJSONTyped(
  value?: WorkspaceCreateInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
  };
}
