/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WorkspaceSchema
 */
export interface WorkspaceSchema {
  /**
   *
   * @type {number}
   * @memberof WorkspaceSchema
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof WorkspaceSchema
   */
  name: string;
  /**
   *
   * @type {boolean}
   * @memberof WorkspaceSchema
   */
  isPersonal: boolean;
  /**
   *
   * @type {Date}
   * @memberof WorkspaceSchema
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof WorkspaceSchema
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the WorkspaceSchema interface.
 */
export function instanceOfWorkspaceSchema(
  value: object,
): value is WorkspaceSchema {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (
    (!("isPersonal" in (value as Record<string, any>)) &&
      !("is_personal" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["isPersonal"] === undefined &&
      (value as Record<string, any>)["is_personal"] === undefined)
  )
    return false;
  if (
    (!("createdAt" in (value as Record<string, any>)) &&
      !("created_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["createdAt"] === undefined &&
      (value as Record<string, any>)["created_at"] === undefined)
  )
    return false;
  if (
    (!("updatedAt" in (value as Record<string, any>)) &&
      !("updated_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["updatedAt"] === undefined &&
      (value as Record<string, any>)["updated_at"] === undefined)
  )
    return false;
  return true;
}

export function WorkspaceSchemaFromJSON(json: any): WorkspaceSchema {
  return WorkspaceSchemaFromJSONTyped(json, false);
}

export function WorkspaceSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceSchema {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    isPersonal: json["is_personal"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function WorkspaceSchemaToJSON(json: any): WorkspaceSchema {
  return WorkspaceSchemaToJSONTyped(json, false);
}

export function WorkspaceSchemaToJSONTyped(
  value?: WorkspaceSchema | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    is_personal: value["isPersonal"],
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
  };
}
