/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StatusInput } from "./StatusInput";
import {
  StatusInputFromJSON,
  StatusInputFromJSONTyped,
  StatusInputToJSON,
  StatusInputToJSONTyped,
} from "./StatusInput";

/**
 * The complete desired workflow for one board.
 *
 * Beyond field shapes, the rules that make a workflow valid (how many statuses,
 * exactly one initial, at least one terminal) live in the domain, so a bad
 * workflow fails the same way whether it arrives over HTTP or from the CLI.
 * @export
 * @interface WorkflowInput
 */
export interface WorkflowInput {
  /**
   *
   * @type {Array<StatusInput>}
   * @memberof WorkflowInput
   */
  statuses: Array<StatusInput>;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof WorkflowInput
   */
  reassign?: { [key: string]: string };
}

/**
 * Check if a given object implements the WorkflowInput interface.
 */
export function instanceOfWorkflowInput(value: object): value is WorkflowInput {
  if (!("statuses" in value) || value["statuses"] === undefined) return false;
  return true;
}

export function WorkflowInputFromJSON(json: any): WorkflowInput {
  return WorkflowInputFromJSONTyped(json, false);
}

export function WorkflowInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkflowInput {
  if (json == null) {
    return json;
  }
  return {
    statuses: (json["statuses"] as Array<any>).map(StatusInputFromJSON),
    reassign: json["reassign"] == null ? undefined : json["reassign"],
  };
}

export function WorkflowInputToJSON(json: any): WorkflowInput {
  return WorkflowInputToJSONTyped(json, false);
}

export function WorkflowInputToJSONTyped(
  value?: WorkflowInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    statuses: (value["statuses"] as Array<any>).map(StatusInputToJSON),
    reassign: value["reassign"],
  };
}
