/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StatusSchema } from "./StatusSchema";
import {
  StatusSchemaFromJSON,
  StatusSchemaFromJSONTyped,
  StatusSchemaToJSON,
  StatusSchemaToJSONTyped,
} from "./StatusSchema";

/**
 * One workspace, with the workflow the inbox board renders as columns.
 *
 * It is also the template every new project's workflow is copied from.
 * @export
 * @interface WorkspaceDetailSchema
 */
export interface WorkspaceDetailSchema {
  /**
   *
   * @type {Array<StatusSchema>}
   * @memberof WorkspaceDetailSchema
   */
  workflow: Array<StatusSchema>;
  /**
   *
   * @type {number}
   * @memberof WorkspaceDetailSchema
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof WorkspaceDetailSchema
   */
  name: string;
  /**
   *
   * @type {boolean}
   * @memberof WorkspaceDetailSchema
   */
  isPersonal: boolean;
  /**
   *
   * @type {Date}
   * @memberof WorkspaceDetailSchema
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof WorkspaceDetailSchema
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the WorkspaceDetailSchema interface.
 */
export function instanceOfWorkspaceDetailSchema(
  value: object,
): value is WorkspaceDetailSchema {
  if (!("workflow" in value) || value["workflow"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (
    (!("isPersonal" in (value as Record<string, any>)) &&
      !("is_personal" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["isPersonal"] === undefined &&
      (value as Record<string, any>)["is_personal"] === undefined)
  )
    return false;
  if (
    (!("createdAt" in (value as Record<string, any>)) &&
      !("created_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["createdAt"] === undefined &&
      (value as Record<string, any>)["created_at"] === undefined)
  )
    return false;
  if (
    (!("updatedAt" in (value as Record<string, any>)) &&
      !("updated_at" in (value as Record<string, any>))) ||
    ((value as Record<string, any>)["updatedAt"] === undefined &&
      (value as Record<string, any>)["updated_at"] === undefined)
  )
    return false;
  return true;
}

export function WorkspaceDetailSchemaFromJSON(
  json: any,
): WorkspaceDetailSchema {
  return WorkspaceDetailSchemaFromJSONTyped(json, false);
}

export function WorkspaceDetailSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceDetailSchema {
  if (json == null) {
    return json;
  }
  return {
    workflow: (json["workflow"] as Array<any>).map(StatusSchemaFromJSON),
    id: json["id"],
    name: json["name"],
    isPersonal: json["is_personal"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function WorkspaceDetailSchemaToJSON(json: any): WorkspaceDetailSchema {
  return WorkspaceDetailSchemaToJSONTyped(json, false);
}

export function WorkspaceDetailSchemaToJSONTyped(
  value?: WorkspaceDetailSchema | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    workflow: (value["workflow"] as Array<any>).map(StatusSchemaToJSON),
    id: value["id"],
    name: value["name"],
    is_personal: value["isPersonal"],
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
  };
}
