/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the ProjectCreateInput interface.
 */
export function instanceOfProjectCreateInput(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    return true;
}
export function ProjectCreateInputFromJSON(json) {
    return ProjectCreateInputFromJSONTyped(json, false);
}
export function ProjectCreateInputFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
    };
}
export function ProjectCreateInputToJSON(json) {
    return ProjectCreateInputToJSONTyped(json, false);
}
export function ProjectCreateInputToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
    };
}
