/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUpdateInput
 */
export interface ProjectUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateInput
     */
    name?: string | null;
}

/**
 * Check if a given object implements the ProjectUpdateInput interface.
 */
export function instanceOfProjectUpdateInput(value: object): value is ProjectUpdateInput {
    return true;
}

export function ProjectUpdateInputFromJSON(json: any): ProjectUpdateInput {
    return ProjectUpdateInputFromJSONTyped(json, false);
}

export function ProjectUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
    };
}

export function ProjectUpdateInputToJSON(json: any): ProjectUpdateInput {
    return ProjectUpdateInputToJSONTyped(json, false);
}

export function ProjectUpdateInputToJSONTyped(value?: ProjectUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

