/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoSchema
 */
export interface TodoSchema {
    /**
     * 
     * @type {number}
     * @memberof TodoSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TodoSchema
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TodoSchema
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoSchema
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof TodoSchema
     */
    projectId: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TodoSchema
     */
    dueDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TodoSchema
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof TodoSchema
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the TodoSchema interface.
 */
export function instanceOfTodoSchema(value: object): value is TodoSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if ((!('dueDate' in (value as Record<string, any>)) && !('due_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['dueDate'] === undefined && (value as Record<string, any>)['due_date'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function TodoSchemaFromJSON(json: any): TodoSchema {
    return TodoSchemaFromJSONTyped(json, false);
}

export function TodoSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'completed': json['completed'],
        'projectId': json['project_id'],
        'dueDate': (json['due_date'] == null ? null : new Date(json['due_date'])),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function TodoSchemaToJSON(json: any): TodoSchema {
    return TodoSchemaToJSONTyped(json, false);
}

export function TodoSchemaToJSONTyped(value?: TodoSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'completed': value['completed'],
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

