/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the TodoCreateInput interface.
 */
export function instanceOfTodoCreateInput(value) {
    if (!('title' in value) || value['title'] === undefined)
        return false;
    return true;
}
export function TodoCreateInputFromJSON(json) {
    return TodoCreateInputFromJSONTyped(json, false);
}
export function TodoCreateInputFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
        'dueDate': json['due_date'] === undefined ? undefined : json['due_date'] === null ? null : (new Date(json['due_date'])),
    };
}
export function TodoCreateInputToJSON(json) {
    return TodoCreateInputToJSONTyped(json, false);
}
export function TodoCreateInputToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
        'description': value['description'],
        'completed': value['completed'],
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0, 10),
    };
}
