/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoProjectInput
 */
export interface TodoProjectInput {
    /**
     * 
     * @type {number}
     * @memberof TodoProjectInput
     */
    projectId?: number | null;
}

/**
 * Check if a given object implements the TodoProjectInput interface.
 */
export function instanceOfTodoProjectInput(value: object): value is TodoProjectInput {
    return true;
}

export function TodoProjectInputFromJSON(json: any): TodoProjectInput {
    return TodoProjectInputFromJSONTyped(json, false);
}

export function TodoProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoProjectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
    };
}

export function TodoProjectInputToJSON(json: any): TodoProjectInput {
    return TodoProjectInputToJSONTyped(json, false);
}

export function TodoProjectInputToJSONTyped(value?: TodoProjectInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
    };
}

