/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoCreateInput
 */
export interface TodoCreateInput {
    /**
     * 
     * @type {string}
     * @memberof TodoCreateInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TodoCreateInput
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoCreateInput
     */
    completed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TodoCreateInput
     */
    projectId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TodoCreateInput
     */
    dueDate?: Date | null;
}

/**
 * Check if a given object implements the TodoCreateInput interface.
 */
export function instanceOfTodoCreateInput(value: object): value is TodoCreateInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TodoCreateInputFromJSON(json: any): TodoCreateInput {
    return TodoCreateInputFromJSONTyped(json, false);
}

export function TodoCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
        'dueDate': json['due_date'] === undefined ? undefined : json['due_date'] === null ? null : (new Date(json['due_date'])),
    };
}

export function TodoCreateInputToJSON(json: any): TodoCreateInput {
    return TodoCreateInputToJSONTyped(json, false);
}

export function TodoCreateInputToJSONTyped(value?: TodoCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'completed': value['completed'],
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
    };
}

