/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoUpdateInput
 */
export interface TodoUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof TodoUpdateInput
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TodoUpdateInput
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TodoUpdateInput
     */
    completed?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof TodoUpdateInput
     */
    projectId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TodoUpdateInput
     */
    dueDate?: Date | null;
}

/**
 * Check if a given object implements the TodoUpdateInput interface.
 */
export function instanceOfTodoUpdateInput(value: object): value is TodoUpdateInput {
    return true;
}

export function TodoUpdateInputFromJSON(json: any): TodoUpdateInput {
    return TodoUpdateInputFromJSONTyped(json, false);
}

export function TodoUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] === undefined ? undefined : json['title'] === null ? null : json['title'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'completed': json['completed'] === undefined ? undefined : json['completed'] === null ? null : json['completed'],
        'projectId': json['project_id'] === undefined ? undefined : json['project_id'] === null ? null : json['project_id'],
        'dueDate': json['due_date'] === undefined ? undefined : json['due_date'] === null ? null : (new Date(json['due_date'])),
    };
}

export function TodoUpdateInputToJSON(json: any): TodoUpdateInput {
    return TodoUpdateInputToJSONTyped(json, false);
}

export function TodoUpdateInputToJSONTyped(value?: TodoUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'completed': value['completed'],
        'project_id': value['projectId'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
    };
}

