/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ProjectCreateInputToJSON, } from '../models/ProjectCreateInput';
import { ProjectSchemaFromJSON, } from '../models/ProjectSchema';
import { ProjectUpdateInputToJSON, } from '../models/ProjectUpdateInput';
import { TodoCreateInputToJSON, } from '../models/TodoCreateInput';
import { TodoSchemaFromJSON, } from '../models/TodoSchema';
import { TodoUpdateInputToJSON, } from '../models/TodoUpdateInput';
import { TokenObtainPairFromJSON, TokenObtainPairToJSON, } from '../models/TokenObtainPair';
import { TokenRefreshFromJSON, TokenRefreshToJSON, } from '../models/TokenRefresh';
/**
 *
 */
export class ApiApi extends runtime.BaseAPI {
    /**
     * Creates request options for apiProjectsCreate without sending the request
     */
    async apiProjectsCreateRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/projects/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateInputToJSON(requestParameters['projectCreateInput']),
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiProjectsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsCreate(requestParameters = {}, initOverrides) {
        const response = await this.apiProjectsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiProjectsDestroy without sending the request
     */
    async apiProjectsDestroyRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling apiProjectsDestroy().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsDestroyRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiProjectsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsDestroy(requestParameters, initOverrides) {
        await this.apiProjectsDestroyRaw(requestParameters, initOverrides);
    }
    /**
     * Creates request options for apiProjectsList without sending the request
     */
    async apiProjectsListRequestOpts() {
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/projects/`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsListRaw(initOverrides) {
        const requestOptions = await this.apiProjectsListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectSchemaFromJSON));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsList(initOverrides) {
        const response = await this.apiProjectsListRaw(initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiProjectsPartialUpdate without sending the request
     */
    async apiProjectsPartialUpdateRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling apiProjectsPartialUpdate().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateInputToJSON(requestParameters['projectUpdateInput']),
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsPartialUpdateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiProjectsPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsPartialUpdate(requestParameters, initOverrides) {
        const response = await this.apiProjectsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiProjectsReorderCreate without sending the request
     */
    async apiProjectsReorderCreateRequestOpts() {
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/projects/reorder/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsReorderCreateRaw(initOverrides) {
        const requestOptions = await this.apiProjectsReorderCreateRequestOpts();
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsReorderCreate(initOverrides) {
        await this.apiProjectsReorderCreateRaw(initOverrides);
    }
    /**
     * Creates request options for apiProjectsRetrieve without sending the request
     */
    async apiProjectsRetrieveRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling apiProjectsRetrieve().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsRetrieveRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiProjectsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsRetrieve(requestParameters, initOverrides) {
        const response = await this.apiProjectsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiTasksCreate without sending the request
     */
    async apiTasksCreateRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/tasks/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoCreateInputToJSON(requestParameters['todoCreateInput']),
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiTasksCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksCreate(requestParameters = {}, initOverrides) {
        const response = await this.apiTasksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiTasksDestroy without sending the request
     */
    async apiTasksDestroyRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling apiTasksDestroy().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksDestroyRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiTasksDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksDestroy(requestParameters, initOverrides) {
        await this.apiTasksDestroyRaw(requestParameters, initOverrides);
    }
    /**
     * Creates request options for apiTasksList without sending the request
     */
    async apiTasksListRequestOpts() {
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/tasks/`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksListRaw(initOverrides) {
        const requestOptions = await this.apiTasksListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoSchemaFromJSON));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksList(initOverrides) {
        const response = await this.apiTasksListRaw(initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiTasksPartialUpdate without sending the request
     */
    async apiTasksPartialUpdateRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling apiTasksPartialUpdate().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TodoUpdateInputToJSON(requestParameters['todoUpdateInput']),
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksPartialUpdateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiTasksPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksPartialUpdate(requestParameters, initOverrides) {
        const response = await this.apiTasksPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiTasksReorderCreate without sending the request
     */
    async apiTasksReorderCreateRequestOpts() {
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/tasks/reorder/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksReorderCreateRaw(initOverrides) {
        const requestOptions = await this.apiTasksReorderCreateRequestOpts();
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksReorderCreate(initOverrides) {
        await this.apiTasksReorderCreateRaw(initOverrides);
    }
    /**
     * Creates request options for apiTasksRetrieve without sending the request
     */
    async apiTasksRetrieveRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling apiTasksRetrieve().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksRetrieveRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiTasksRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }
    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksRetrieve(requestParameters, initOverrides) {
        const response = await this.apiTasksRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiTokenCreate without sending the request
     */
    async apiTokenCreateRequestOpts(requestParameters) {
        if (requestParameters['tokenObtainPair'] == null) {
            throw new runtime.RequiredError('tokenObtainPair', 'Required parameter "tokenObtainPair" was null or undefined when calling apiTokenCreate().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/api/token/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenObtainPairToJSON(requestParameters['tokenObtainPair']),
        };
    }
    /**
     * Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
     */
    async apiTokenCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiTokenCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => TokenObtainPairFromJSON(jsonValue));
    }
    /**
     * Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
     */
    async apiTokenCreate(requestParameters, initOverrides) {
        const response = await this.apiTokenCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for apiTokenRefreshCreate without sending the request
     */
    async apiTokenRefreshCreateRequestOpts(requestParameters) {
        if (requestParameters['tokenRefresh'] == null) {
            throw new runtime.RequiredError('tokenRefresh', 'Required parameter "tokenRefresh" was null or undefined when calling apiTokenRefreshCreate().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/api/token/refresh/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshToJSON(requestParameters['tokenRefresh']),
        };
    }
    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     */
    async apiTokenRefreshCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.apiTokenRefreshCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => TokenRefreshFromJSON(jsonValue));
    }
    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     */
    async apiTokenRefreshCreate(requestParameters, initOverrides) {
        const response = await this.apiTokenRefreshCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
