/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProjectCreateInput,
    ProjectCreateInputFromJSON,
    ProjectCreateInputToJSON,
} from '../models/ProjectCreateInput';
import {
    type ProjectSchema,
    ProjectSchemaFromJSON,
    ProjectSchemaToJSON,
} from '../models/ProjectSchema';
import {
    type ProjectUpdateInput,
    ProjectUpdateInputFromJSON,
    ProjectUpdateInputToJSON,
} from '../models/ProjectUpdateInput';
import {
    type TodoCreateInput,
    TodoCreateInputFromJSON,
    TodoCreateInputToJSON,
} from '../models/TodoCreateInput';
import {
    type TodoSchema,
    TodoSchemaFromJSON,
    TodoSchemaToJSON,
} from '../models/TodoSchema';
import {
    type TodoUpdateInput,
    TodoUpdateInputFromJSON,
    TodoUpdateInputToJSON,
} from '../models/TodoUpdateInput';

export interface ApiProjectsCreateRequest {
    projectCreateInput?: ProjectCreateInput;
}

export interface ApiProjectsDestroyRequest {
    id: string;
}

export interface ApiProjectsPartialUpdateRequest {
    id: string;
    projectUpdateInput?: ProjectUpdateInput;
}

export interface ApiProjectsRetrieveRequest {
    id: string;
}

export interface ApiSchemaRetrieveRequest {
    format?: ApiSchemaRetrieveFormatEnum;
    lang?: ApiSchemaRetrieveLangEnum;
}

export interface ApiTasksCreateRequest {
    todoCreateInput?: TodoCreateInput;
}

export interface ApiTasksDestroyRequest {
    id: string;
}

export interface ApiTasksPartialUpdateRequest {
    id: string;
    todoUpdateInput?: TodoUpdateInput;
}

export interface ApiTasksRetrieveRequest {
    id: string;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiProjectsCreate without sending the request
     */
    async apiProjectsCreateRequestOpts(requestParameters: ApiProjectsCreateRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/projects/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateInputToJSON(requestParameters['projectCreateInput']),
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsCreateRaw(requestParameters: ApiProjectsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSchema>> {
        const requestOptions = await this.apiProjectsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsCreate(requestParameters: ApiProjectsCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSchema> {
        const response = await this.apiProjectsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProjectsDestroy without sending the request
     */
    async apiProjectsDestroyRequestOpts(requestParameters: ApiProjectsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsDestroyRaw(requestParameters: ApiProjectsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiProjectsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsDestroy(requestParameters: ApiProjectsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProjectsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiProjectsList without sending the request
     */
    async apiProjectsListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/projects/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectSchema>>> {
        const requestOptions = await this.apiProjectsListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectSchemaFromJSON));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectSchema>> {
        const response = await this.apiProjectsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProjectsPartialUpdate without sending the request
     */
    async apiProjectsPartialUpdateRequestOpts(requestParameters: ApiProjectsPartialUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateInputToJSON(requestParameters['projectUpdateInput']),
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsPartialUpdateRaw(requestParameters: ApiProjectsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSchema>> {
        const requestOptions = await this.apiProjectsPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsPartialUpdate(requestParameters: ApiProjectsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSchema> {
        const response = await this.apiProjectsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiProjectsReorderCreate without sending the request
     */
    async apiProjectsReorderCreateRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/projects/reorder/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsReorderCreateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiProjectsReorderCreateRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsReorderCreate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProjectsReorderCreateRaw(initOverrides);
    }

    /**
     * Creates request options for apiProjectsRetrieve without sending the request
     */
    async apiProjectsRetrieveRequestOpts(requestParameters: ApiProjectsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsRetrieveRaw(requestParameters: ApiProjectsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectSchema>> {
        const requestOptions = await this.apiProjectsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectSchemaFromJSON(jsonValue));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiProjectsRetrieve(requestParameters: ApiProjectsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectSchema> {
        const response = await this.apiProjectsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiSchemaRetrieve without sending the request
     */
    async apiSchemaRetrieveRequestOpts(requestParameters: ApiSchemaRetrieveRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/schema/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
     */
    async apiSchemaRetrieveRaw(requestParameters: ApiSchemaRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.apiSchemaRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
     */
    async apiSchemaRetrieve(requestParameters: ApiSchemaRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.apiSchemaRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksCreate without sending the request
     */
    async apiTasksCreateRequestOpts(requestParameters: ApiTasksCreateRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/tasks/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoCreateInputToJSON(requestParameters['todoCreateInput']),
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksCreateRaw(requestParameters: ApiTasksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoSchema>> {
        const requestOptions = await this.apiTasksCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksCreate(requestParameters: ApiTasksCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoSchema> {
        const response = await this.apiTasksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksDestroy without sending the request
     */
    async apiTasksDestroyRequestOpts(requestParameters: ApiTasksDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksDestroyRaw(requestParameters: ApiTasksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTasksDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksDestroy(requestParameters: ApiTasksDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTasksDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiTasksList without sending the request
     */
    async apiTasksListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/tasks/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoSchema>>> {
        const requestOptions = await this.apiTasksListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoSchemaFromJSON));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoSchema>> {
        const response = await this.apiTasksListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksPartialUpdate without sending the request
     */
    async apiTasksPartialUpdateRequestOpts(requestParameters: ApiTasksPartialUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TodoUpdateInputToJSON(requestParameters['todoUpdateInput']),
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksPartialUpdateRaw(requestParameters: ApiTasksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoSchema>> {
        const requestOptions = await this.apiTasksPartialUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksPartialUpdate(requestParameters: ApiTasksPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoSchema> {
        const response = await this.apiTasksPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTasksReorderCreate without sending the request
     */
    async apiTasksReorderCreateRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/tasks/reorder/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksReorderCreateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTasksReorderCreateRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksReorderCreate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTasksReorderCreateRaw(initOverrides);
    }

    /**
     * Creates request options for apiTasksRetrieve without sending the request
     */
    async apiTasksRetrieveRequestOpts(requestParameters: ApiTasksRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTasksRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/tasks/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksRetrieveRaw(requestParameters: ApiTasksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoSchema>> {
        const requestOptions = await this.apiTasksRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoSchemaFromJSON(jsonValue));
    }

    /**
     * This is the magic.  Overrides `.as_view()` so that it takes an `actions` keyword that performs the binding of HTTP methods to actions on the Resource.  For example, to create a concrete view binding the \'GET\' and \'POST\' methods to the \'alist\' and \'acreate\' actions...  view = MyViewSet.as_view({\'get\': \'alist\', \'post\': \'acreate\'})
     */
    async apiTasksRetrieve(requestParameters: ApiTasksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoSchema> {
        const response = await this.apiTasksRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiSchemaRetrieveFormatEnum = {
    Json: 'json',
    Yaml: 'yaml'
} as const;
export type ApiSchemaRetrieveFormatEnum = typeof ApiSchemaRetrieveFormatEnum[keyof typeof ApiSchemaRetrieveFormatEnum];
/**
 * @export
 */
export const ApiSchemaRetrieveLangEnum = {
    Af: 'af',
    Ar: 'ar',
    ArDz: 'ar-dz',
    Ast: 'ast',
    Az: 'az',
    Be: 'be',
    Bg: 'bg',
    Bn: 'bn',
    Br: 'br',
    Bs: 'bs',
    Ca: 'ca',
    Ckb: 'ckb',
    Cs: 'cs',
    Cy: 'cy',
    Da: 'da',
    De: 'de',
    Dsb: 'dsb',
    El: 'el',
    En: 'en',
    EnAu: 'en-au',
    EnGb: 'en-gb',
    Eo: 'eo',
    Es: 'es',
    EsAr: 'es-ar',
    EsCo: 'es-co',
    EsMx: 'es-mx',
    EsNi: 'es-ni',
    EsVe: 'es-ve',
    Et: 'et',
    Eu: 'eu',
    Fa: 'fa',
    Fi: 'fi',
    Fr: 'fr',
    Fy: 'fy',
    Ga: 'ga',
    Gd: 'gd',
    Gl: 'gl',
    He: 'he',
    Hi: 'hi',
    Hr: 'hr',
    Hsb: 'hsb',
    Ht: 'ht',
    Hu: 'hu',
    Hy: 'hy',
    Ia: 'ia',
    Id: 'id',
    Ig: 'ig',
    Io: 'io',
    Is: 'is',
    It: 'it',
    Ja: 'ja',
    Ka: 'ka',
    Kab: 'kab',
    Kk: 'kk',
    Km: 'km',
    Kn: 'kn',
    Ko: 'ko',
    Ky: 'ky',
    Lb: 'lb',
    Lt: 'lt',
    Lv: 'lv',
    Mk: 'mk',
    Ml: 'ml',
    Mn: 'mn',
    Mr: 'mr',
    Ms: 'ms',
    My: 'my',
    Nb: 'nb',
    Ne: 'ne',
    Nl: 'nl',
    Nn: 'nn',
    Os: 'os',
    Pa: 'pa',
    Pl: 'pl',
    Pt: 'pt',
    PtBr: 'pt-br',
    Ro: 'ro',
    Ru: 'ru',
    Sk: 'sk',
    Sl: 'sl',
    Sq: 'sq',
    Sr: 'sr',
    SrLatn: 'sr-latn',
    Sv: 'sv',
    Sw: 'sw',
    Ta: 'ta',
    Te: 'te',
    Tg: 'tg',
    Th: 'th',
    Tk: 'tk',
    Tr: 'tr',
    Tt: 'tt',
    Udm: 'udm',
    Ug: 'ug',
    Uk: 'uk',
    Ur: 'ur',
    Uz: 'uz',
    Vi: 'vi',
    ZhHans: 'zh-hans',
    ZhHant: 'zh-hant'
} as const;
export type ApiSchemaRetrieveLangEnum = typeof ApiSchemaRetrieveLangEnum[keyof typeof ApiSchemaRetrieveLangEnum];
