/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ProjectCreateInputToJSON, } from '../models/ProjectCreateInput';
/**
 *
 */
export class ProjectsApi extends runtime.BaseAPI {
    /**
     * Creates request options for projectsCreateCreate without sending the request
     */
    async projectsCreateCreateRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/projects/create/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateInputToJSON(requestParameters['projectCreateInput']),
        };
    }
    /**
     */
    async projectsCreateCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.projectsCreateCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async projectsCreateCreate(requestParameters = {}, initOverrides) {
        const response = await this.projectsCreateCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for projectsRetrieve without sending the request
     */
    async projectsRetrieveRequestOpts() {
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/projects/`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     */
    async projectsRetrieveRaw(initOverrides) {
        const requestOptions = await this.projectsRetrieveRequestOpts();
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async projectsRetrieve(initOverrides) {
        const response = await this.projectsRetrieveRaw(initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for projectsRetrieve2 without sending the request
     */
    async projectsRetrieve2RequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling projectsRetrieve2().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/projects/{id}/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     */
    async projectsRetrieve2Raw(requestParameters, initOverrides) {
        const requestOptions = await this.projectsRetrieve2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async projectsRetrieve2(requestParameters, initOverrides) {
        const response = await this.projectsRetrieve2Raw(requestParameters, initOverrides);
        return await response.value();
    }
}
