/* tslint:disable */
/* eslint-disable */
/**
 * Sturdy Potato API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { TodoCreateInputToJSON, } from '../models/TodoCreateInput';
import { TodoProjectInputToJSON, } from '../models/TodoProjectInput';
/**
 *
 */
export class TasksApi extends runtime.BaseAPI {
    /**
     * Creates request options for tasksCreateCreate without sending the request
     */
    async tasksCreateCreateRequestOpts(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/tasks/create/`;
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoCreateInputToJSON(requestParameters['todoCreateInput']),
        };
    }
    /**
     */
    async tasksCreateCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.tasksCreateCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async tasksCreateCreate(requestParameters = {}, initOverrides) {
        const response = await this.tasksCreateCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for tasksProjectCreate without sending the request
     */
    async tasksProjectCreateRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling tasksProjectCreate().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/tasks/{id}/project/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoProjectInputToJSON(requestParameters['todoProjectInput']),
        };
    }
    /**
     */
    async tasksProjectCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.tasksProjectCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async tasksProjectCreate(requestParameters, initOverrides) {
        const response = await this.tasksProjectCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for tasksRetrieve without sending the request
     */
    async tasksRetrieveRequestOpts() {
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/tasks/`;
        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     */
    async tasksRetrieveRaw(initOverrides) {
        const requestOptions = await this.tasksRetrieveRequestOpts();
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async tasksRetrieve(initOverrides) {
        const response = await this.tasksRetrieveRaw(initOverrides);
        return await response.value();
    }
    /**
     * Creates request options for tasksToggleCreate without sending the request
     */
    async tasksToggleCreateRequestOpts(requestParameters) {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError('id', 'Required parameter "id" was null or undefined when calling tasksToggleCreate().');
        }
        const queryParameters = {};
        const headerParameters = {};
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);
            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        let urlPath = `/tasks/{id}/toggle/`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }
    /**
     */
    async tasksToggleCreateRaw(requestParameters, initOverrides) {
        const requestOptions = await this.tasksToggleCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);
        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse(response);
        }
        else {
            return new runtime.TextApiResponse(response);
        }
    }
    /**
     */
    async tasksToggleCreate(requestParameters, initOverrides) {
        const response = await this.tasksToggleCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
