"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-ykaf2t*o!v0q!z-da^c@ddb2kuu9c58t!1y84sz0jl^o4l*aim",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1").lower() in {
    "1",
    "true",
    "yes",
    "on",
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

# Origins (scheme + host) allowed to send unsafe requests (e.g. admin POSTs).
# Required for CSRF checks when served over HTTPS behind a reverse proxy.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Trust the X-Forwarded-Proto header set by nginx so Django knows the original
# request was HTTPS. Without this, CSRF/redirect logic treats requests as http.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security hardening, enabled automatically whenever DEBUG is off (production).
# Expressed as assignments derived from DEBUG rather than an `if not DEBUG:`
# block so every line always executes (keeps settings fully covered) and the
# secure defaults can never be silently skipped in a misconfigured deploy.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31_536_000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "config.apps.ConfigConfig",
    "infrastructure.apps.InfrastructureConfig",
    "api.apps.ApiConfig",
    "web.apps.WebConfig",
    "serializers.apps.SerializersConfig",
]

AUTH_USER_MODEL = "infrastructure.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# django-browser-reload: development-only live reload for templates and static
# files. Gated on DEBUG so it is never wired in production (and the dependency
# lives in the dev group). Tests run with DEBUG on, so these lines stay covered.
if DEBUG:
    INSTALLED_APPS += ["django_browser_reload"]
    MIDDLEWARE += ["django_browser_reload.middleware.BrowserReloadMiddleware"]

ROOT_URLCONF = "config.urls"

LOGIN_REDIRECT_URL = "home-page"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(
            os.environ.get("DJANGO_DB_PATH", str(BASE_DIR.parent / "db.sqlite3"))
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR.parent / "static",
]
STATIC_ROOT = BASE_DIR.parent / "staticfiles"

STORAGES = {
    "staticfiles": {
        # Hashed/compressed manifest storage in production; plain storage in
        # development so templates can resolve {% static %} without first
        # running collectstatic (the manifest backend errors on missing entries).
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Vite dev mode follows DEBUG, but can be forced off (e.g. for e2e tests) so
# templates use the built assets from manifest.json instead of the Vite dev
# server. Set DJANGO_VITE_DEV_MODE=false after running `npm run build`.
_vite_dev_mode = os.environ.get("DJANGO_VITE_DEV_MODE")
DJANGO_VITE = {
    "default": {
        "dev_mode": (
            DEBUG
            if _vite_dev_mode is None
            else _vite_dev_mode.lower() in {"1", "true", "yes", "on"}
        ),
        "manifest_path": BASE_DIR.parent / "static" / "manifest.json",
    }
}

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Session auth stays first so the server-rendered web app and browsable API
    # keep their existing behaviour (a credential-less request gets 403, not the
    # 401 that a JWT-first order would return). JWTAuthentication runs next: with
    # no session cookie SessionAuthentication returns None, so a request bearing
    # an Authorization: Bearer <token> header is authenticated via JWT. This is
    # what lets the React SPA talk to the same endpoints with a token.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# JSON Web Token settings. Access tokens are short-lived; the SPA refreshes them
# with the longer-lived refresh token via /api/token/refresh/.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# Advertise the bearer scheme in the OpenAPI schema so the generated TypeScript
# client wires up `accessToken`. drf-spectacular auto-detects JWTAuthentication.
SPECTACULAR_SETTINGS = {
    "TITLE": "Sturdy Potato API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Cross-origin requests from the Vite dev server (React SPA on another origin).
# Bearer tokens are sent in the Authorization header, so credentialed cookies
# are not required here.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if origin.strip()
]

# Logging: stream to stdout so the container runtime collects it. Level is
# overridable per-deploy via DJANGO_LOG_LEVEL without touching code.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
