# Generated by Django 6.1 on 2026-08-16

from typing import Any

from django.db import migrations, models


def backfill_positions(apps: Any, schema_editor: Any) -> None:
    Project = apps.get_model("infrastructure", "Project")
    Todo = apps.get_model("infrastructure", "Todo")

    for user_id in Project.objects.values_list("user_id", flat=True).distinct():
        projects = list(Project.objects.filter(user_id=user_id).order_by("name", "id"))
        for position, project in enumerate(projects):
            project.position = position
        Project.objects.bulk_update(projects, ["position"])

    for user_id in Todo.objects.values_list("user_id", flat=True).distinct():
        tasks = list(
            Todo.objects.filter(user_id=user_id).order_by(
                "completed", "due_date", "-created_at", "-id"
            )
        )
        for position, task in enumerate(tasks):
            task.position = position
        Todo.objects.bulk_update(tasks, ["position"])


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0003_todo_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="todo",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_positions, migrations.RunPython.noop),
    ]
