# Generated by Django 6.1 on 2026-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_project_todo_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="todo",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "position"], name="infrastruct_user_id_0e186b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "position"], name="todo_todo_user_id_f40d10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "completed", "position"],
                name="todo_todo_user_id_b55871_idx",
            ),
        ),
    ]
